name: Databricks Asset Bundles CI

on:
  pull_request:
    branches:
      - main
      - feature/dabsdeploy
  push:
    branches:
      - main
      - feature/dabsdeploy

jobs:
  validate-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main
        env:
          DATABRICKS_HOST: 'https://e2-demo-field-eng.cloud.databricks.com'
          DATABRICKS_TOKEN: ${{ secrets.DEPLOY_NOTEBOOK_TOKEN }}
          # To use OAuth client credentials instead of token, comment out the above line and uncomment below:
          # DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          # DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
          # DATABRICKS_ACCOUNT_ID: ${{ secrets.DATABRICKS_ACCOUNT_ID }}  # Optional, only needed for account-level operations

      - name: Validate bundle
        run: databricks bundle validate

      - name: Deploy to CI environment
        if: github.event_name == 'pull_request'
        run: |
          export PR_NUMBER=${{ github.event.number }}
          databricks bundle deploy --target dev --var="environment=pr-${PR_NUMBER}"

      - name: Run workflow tests
        if: github.event_name == 'pull_request'
        run: |
          export PR_NUMBER=${{ github.event.number }}
          databricks bundle run demo_workflow --target dev

      - name: Deploy to main or feature/dabsdeploy
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/dabsdeploy')
        run: databricks bundle deploy --target dev

      - name: Cleanup PR deployment
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: |
          export PR_NUMBER=${{ github.event.number }}
          databricks bundle destroy --target dev --var="environment=pr-${PR_NUMBER}" || true
