name: Databricks Asset Bundles CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Databricks CLI
        run: |
          pip install --upgrade pip
          pip install databricks-cli

      - name: Configure Databricks CLI
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST || 'https://e2-demo-field-eng.cloud.databricks.com/' }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          if [ -z "$DATABRICKS_TOKEN" ]; then
            echo "❌ DATABRICKS_TOKEN secret not found!"
            echo "Please add DATABRICKS_TOKEN to your repository secrets."
            echo "See README.md for setup instructions."
            exit 1
          fi
          cat > ~/.databrickscfg << EOF
          [DEFAULT]
          host = $DATABRICKS_HOST
          token = $DATABRICKS_TOKEN
          EOF

      - name: Validate bundle
        run: databricks bundle validate

      - name: Deploy to CI environment
        if: github.event_name == 'pull_request'
        run: |
          # Create a unique target for this PR
          export PR_NUMBER=${{ github.event.number }}
          databricks bundle deploy --target dev --var="environment=pr-${PR_NUMBER}"

      - name: Run workflow tests
        if: github.event_name == 'pull_request'
        run: |
          export PR_NUMBER=${{ github.event.number }}
          databricks bundle run demo_workflow --target dev

      - name: Deploy to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: databricks bundle deploy --target dev

      - name: Cleanup PR deployment
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: |
          export PR_NUMBER=${{ github.event.number }}
          databricks bundle destroy --target dev --var="environment=pr-${PR_NUMBER}" || true 